USE HOTEL;

DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS PAYMENT;

CREATE TABLE CUSTOMER (
CUSTOMER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(25),
LAST_NAME VARCHAR(25),
ADDRESS VARCHAR(45),
CITY VARCHAR(25),
STATE VARCHAR(25),
PHONE VARCHAR(25)
) ENGINE=INNODB;

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(45),
PASSWORD VARCHAR(250),
TOKEN VARCHAR(250),
ROLES VARCHAR(45)
) ENGINE=INNODB;

-- Make the field USERNAME indexed and unique
ALTER TABLE EMPLOYEE ADD UNIQUE (USERNAME);

CREATE TABLE ROOM (
ROOM_NUMBER INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
ROOM_PRICE DECIMAL(7,2),
ROOM_TYPE VARCHAR(45),
DESCRIPTION TEXT
) ENGINE=INNODB;

CREATE TABLE RESERVATION (
RESERVATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
CHECKIN_DATE TIMESTAMP,
CHECKOUT_DATE TIMESTAMP,
CUSTOMER_ID INT UNSIGNED NOT NULL,
ROOM_NUMBER INT UNSIGNED NOT NULL,
EMPLOYEE_ID INT UNSIGNED NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOM(ROOM_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE PAYMENT (
PAYMENT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
CARD_TYPE VARCHAR(20),
CARD_NUMBER VARCHAR(20),
CARD_EXPIRATION VARCHAR(45),
PAYMENT_AMOUNT DECIMAL(7,2),
DESCRIPTION TEXT,
CUSTOMER_ID INT UNSIGNED NOT NULL,
RESERVATION_ID INT UNSIGNED NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION(RESERVATION_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=INNODB;

-- Add indexes for commonly searched columns 
ALTER TABLE CUSTOMER ADD INDEX(CUSTOMER_ID);
ALTER TABLE RESERVATION ADD INDEX(RESERVATION_ID);
ALTER TABLE PAYMENT ADD INDEX(PAYMENT_ID);

-- Inserts data into the CLIENTS table
INSERT INTO EMPLOYEE (EMPLOYEE_ID, USERNAME, PASSWORD, TOKEN, ROLES) VALUES (NULL, "manager", "IIQ8CRls8Ubk4qKotYAIU3jUGQnkP+FItRpkPC6K6xg=$6aFVOnb9Jgf5q8qfRMZ7kp8cntDlqlnlWteKL9wNgUE=", "e24rrrwe22r=TOKEN_PLACEHOLDER", "admin");
