USE HOTEL;

DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS PAYMENT;

CREATE TABLE CUSTOMER (
CUSTOMER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(25),
LAST_NAME VARCHAR(25),
ADDRESS VARCHAR(45),
CITY VARCHAR(25),
STATE VARCHAR(25),
PHONE VARCHAR(25)
) ENGINE=INNODB;

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(45),
PASSWORD VARCHAR(250),
TOKEN VARCHAR(250),
ROLES VARCHAR(45)
) ENGINE=INNODB;

-- Make the field USERNAME indexed and unique
ALTER TABLE EMPLOYEE ADD UNIQUE (USERNAME);

CREATE TABLE ROOM (
ROOM_NUMBER INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
ROOM_PRICE DECIMAL(7,2),
ROOM_TYPE VARCHAR(45),
IMAGE VARCHAR(225),
DESCRIPTION TEXT
) ENGINE=INNODB;

CREATE TABLE RESERVATION (
RESERVATION_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
CHECKIN_DATE TIMESTAMP,
CHECKOUT_DATE TIMESTAMP,
CUSTOMER_ID INT UNSIGNED NOT NULL,
ROOM_NUMBER INT UNSIGNED NOT NULL,
EMPLOYEE_ID INT UNSIGNED NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOM(ROOM_NUMBER)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE PAYMENT (
PAYMENT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
CARD_TYPE VARCHAR(20),
CARD_NUMBER VARCHAR(20),
CARD_EXPIRATION VARCHAR(45),
PAYMENT_AMOUNT DECIMAL(7,2),
DESCRIPTION TEXT,
CUSTOMER_ID INT UNSIGNED NOT NULL,
RESERVATION_ID INT UNSIGNED NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION(RESERVATION_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
) ENGINE=INNODB;

-- Add indexes for commonly searched columns 
ALTER TABLE CUSTOMER ADD INDEX(CUSTOMER_ID);
ALTER TABLE RESERVATION ADD INDEX(RESERVATION_ID);
ALTER TABLE PAYMENT ADD INDEX(PAYMENT_ID);

-- Inserts data into the EMPLOYEE table
INSERT INTO EMPLOYEE (EMPLOYEE_ID, USERNAME, PASSWORD, TOKEN, ROLES) VALUES (NULL, "manager", "IIQ8CRls8Ubk4qKotYAIU3jUGQnkP+FItRpkPC6K6xg=$6aFVOnb9Jgf5q8qfRMZ7kp8cntDlqlnlWteKL9wNgUE=", "e24rrrwe22r=TOKEN_PLACEHOLDER", "admin");

-- Inserts data into the CUSTOMER table
INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS, CITY, STATE, PHONE) VALUES (NULL, "John", "Smith", "123 McGill College", "Montreal", "Quebec", "514-123-4567");

-- Inserts data into the ROOM table
INSERT INTO ROOM (ROOM_NUMBER, ROOM_PRICE, ROOM_TYPE, IMAGE, DESCRIPTION) VALUES (NULL, 150.00, "Single", "room1.jpg", "Cozy and comfortable recently renovated room with double bed, microwave and coffe maker.");

-- Inserts data into the RESERVATION table
INSERT INTO RESERVATION (RESERVATION_ID, CHECKIN_DATE, CHECKOUT_DATE, CUSTOMER_ID, ROOM_NUMBER, EMPLOYEE_ID) VALUES (NULL, "2017-01-10", "2017-01-16", 1, 1, 1);

-- Inserts data into the PAYMENT table
INSERT INTO PAYMENT (PAYMENT_ID, CARD_TYPE, CARD_NUMBER, CARD_EXPIRATION, PAYMENT_AMOUNT, DESCRIPTION, CUSTOMER_ID, RESERVATION_ID) VALUES (NULL, "VISA", "4444 4444 4444 4444", "05/2020", 230.50, "Hotel room booking for conference", 1, 1);